-- ==========================================
-- 1. สร้างตารางแบบบ้าน (houses)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.houses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    building_type TEXT DEFAULT 'บ้าน',
    price NUMERIC DEFAULT 0,
    width NUMERIC DEFAULT 0,
    length NUMERIC DEFAULT 0,
    bedrooms INTEGER DEFAULT 0,
    bathrooms INTEGER DEFAULT 0,
    parking INTEGER DEFAULT 0,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 2. สร้างตารางเก็บรูปภาพประกอบแบบบ้าน (house_images)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.house_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id UUID REFERENCES public.houses(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 3. ตั้งค่าความปลอดภัยพื้นฐาน (RLS Policies)
-- เพื่อให้แอดมินแก้ไขได้ และลูกค้าดูบนเว็บไซต์ได้
-- ==========================================
ALTER TABLE public.houses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.house_images ENABLE ROW LEVEL SECURITY;

-- 3.1 สิทธิ์สำหรับการดึงข้อมูลมาแสดงหน้าเว็บ (ทุกคนดูได้)
CREATE POLICY "อนุญาตให้ทุกคนดูแบบบ้านบนหน้าเว็บได้" 
ON public.houses FOR SELECT USING (true);

CREATE POLICY "อนุญาตให้ทุกคนดูรูปภาพแบบบ้านได้" 
ON public.house_images FOR SELECT USING (true);

-- 3.2 สิทธิ์สำหรับการสร้างแก้ไข (เปิดให้สาธารณะชั่วคราว หรือใช้ของแอดมิน)
CREATE POLICY "อนุญาตการแก้ไขตาราง houses"
ON public.houses FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "อนุญาตการแก้ไขตาราง house_images"
ON public.house_images FOR ALL USING (true) WITH CHECK (true);
